spring:
  application:
    name: booksapi
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:54322}/${DB_NAME:books}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:user}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: ${SHOW_SQL:true}
  flyway:
    enabled: true
    locations: classpath:db.migration/general,classpath:db.migration/inserts
    schemas: public
auth:
  jwt:
    secret: ${JWT_SECRET:3f46afdd68a5ccef651212f60986f1a8bd918d582eca67e15ddd1d4e7620b24a}
    expiration-days: 30
    issuer: booksapi
booksapi:
  http:
    client:
      config:
        connection-timeout: 5000
        read-timeout: 5000
        uri: https://openlibrary.org/search.json
        limit: 1
        fields:
          - author_name
          - first_publish_year
          - isbn