spring:
  application:
    name: booksapi
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:54322}/${DB_NAME:books}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:user}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: ${SHOW_SQL:true}
  flyway:
    enabled: true
    locations: classpath:db.migration/general,classpath:db.migration/inserts
    schemas: public
